# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(40, 43, 75, 255));\n"
"border-radius: 10px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title_bar.setStyleSheet("background-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout.setContentsMargins(15, 5, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(100, 194, 202);")
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_minimize.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 150, 0);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_maximize.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_maximize.setFont(font)
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 150, 0);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_3.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_close.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(153, 0, 0);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_2.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color: none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_bar)
        self.stackedWidget.setStyleSheet("background-color: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_home = QtWidgets.QFrame(self.page_home)
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setObjectName("frame_content_home")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_content_home)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_info = QtWidgets.QFrame(self.frame_content_home)
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_circle_1 = QtWidgets.QFrame(self.frame_info)
        self.frame_circle_1.setMinimumSize(QtCore.QSize(210, 210))
        self.frame_circle_1.setMaximumSize(QtCore.QSize(210, 210))
        self.frame_circle_1.setStyleSheet("QFrame{\n"
"border: 5px solid rgb(100, 194, 202);\n"
"border-radius: 105px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"border: 5px solid rgb(74, 145, 150);\n"
"}")
        self.frame_circle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_1.setObjectName("frame_circle_1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_circle_1)
        self.verticalLayout_10.setContentsMargins(-1, 30, -1, 40)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;\n"
"color: rgb(100, 194, 202);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Manjari")
        font.setPointSize(40)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: none;\n"
"color: rgb(189, 189, 189);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_circle_1)
        self.label_19.setMinimumSize(QtCore.QSize(180, 0))
        self.label_19.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: none;\n"
"color: rgb(200, 200, 200);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: none;\n"
"color: rgb(85, 255, 127);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.horizontalLayout_4.addWidget(self.frame_circle_1)
        self.frame_circle_2 = QtWidgets.QFrame(self.frame_info)
        self.frame_circle_2.setMinimumSize(QtCore.QSize(210, 210))
        self.frame_circle_2.setMaximumSize(QtCore.QSize(210, 210))
        self.frame_circle_2.setStyleSheet("QFrame{\n"
"border: 5px solid rgb(100, 194, 202);\n"
"border-radius: 105px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"border: 5px solid rgb(74, 145, 150);\n"
"}")
        self.frame_circle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_2.setObjectName("frame_circle_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_circle_2)
        self.verticalLayout_9.setContentsMargins(-1, 30, -1, 40)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border: none;\n"
"color: rgb(100, 194, 202);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Manjari")
        font.setPointSize(40)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: none;\n"
"color: rgb(189, 189, 189);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_circle_2)
        self.label_15.setMinimumSize(QtCore.QSize(180, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border: none;\n"
"color: rgb(200, 200, 200);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;\n"
"color: rgb(85, 255, 127);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.horizontalLayout_4.addWidget(self.frame_circle_2)
        self.frame_circle_3 = QtWidgets.QFrame(self.frame_info)
        self.frame_circle_3.setMinimumSize(QtCore.QSize(210, 210))
        self.frame_circle_3.setMaximumSize(QtCore.QSize(210, 210))
        self.frame_circle_3.setStyleSheet("QFrame{\n"
"border: 5px solid rgb(100, 194, 202);\n"
"border-radius: 105px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"border: 5px solid rgb(74, 145, 150);\n"
"}")
        self.frame_circle_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_3.setObjectName("frame_circle_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_circle_3)
        self.verticalLayout_11.setContentsMargins(-1, 30, -1, 40)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"color: rgb(100, 194, 202);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Manjari")
        font.setPointSize(40)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border: none;\n"
"color: rgb(189, 189, 189);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_11.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_circle_3)
        self.label_23.setMinimumSize(QtCore.QSize(180, 0))
        self.label_23.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("border: none;\n"
"color: rgb(200, 200, 200);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_11.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("border: none;\n"
"color: rgb(85, 255, 127);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_11.addWidget(self.label_24)
        self.horizontalLayout_4.addWidget(self.frame_circle_3)
        self.verticalLayout_12.addWidget(self.frame_info)
        self.frame_text = QtWidgets.QFrame(self.frame_content_home)
        self.frame_text.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text.setObjectName("frame_text")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_text)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.frame_text)
        self.label_25.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(40, 43, 75, 255));\n"
"border-radius: 10px;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.verticalLayout_12.addWidget(self.frame_text)
        self.verticalLayout_5.addWidget(self.frame_content_home)
        self.stackedWidget.addWidget(self.page_home)
        self.page_credit = QtWidgets.QWidget()
        self.page_credit.setObjectName("page_credit")
        self.frame_content_credit = QtWidgets.QFrame(self.page_credit)
        self.frame_content_credit.setGeometry(QtCore.QRect(90, 120, 120, 80))
        self.frame_content_credit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_credit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_credit.setObjectName("frame_content_credit")
        self.stackedWidget.addWidget(self.page_credit)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color: none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credit = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credit.setObjectName("frame_label_credit")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_label_credit)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credit = QtWidgets.QLabel(self.frame_label_credit)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_credit.setFont(font)
        self.label_credit.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_credit.setObjectName("label_credit")
        self.verticalLayout_3.addWidget(self.label_credit)
        self.horizontalLayout_2.addWidget(self.frame_label_credit)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout_2.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "System Monitor"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize Window"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize Window"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close Window"))
        self.label_17.setText(_translate("MainWindow", "CPU USAGE"))
        self.label_18.setText(_translate("MainWindow", "25%"))
        self.label_19.setText(_translate("MainWindow", "Intel(R) Core(TM) i3-6006U, 2.00GHz"))
        self.label_20.setText(_translate("MainWindow", "Temp: 45C°"))
        self.label_13.setText(_translate("MainWindow", "GPU USAGE"))
        self.label_14.setText(_translate("MainWindow", "10%"))
        self.label_15.setText(_translate("MainWindow", "Intel HD Graphics 520"))
        self.label_16.setText(_translate("MainWindow", "Temp: 40C°"))
        self.label_21.setText(_translate("MainWindow", "RAM USAGE"))
        self.label_22.setText(_translate("MainWindow", "70%"))
        self.label_23.setText(_translate("MainWindow", "DDR4 4GB"))
        self.label_24.setText(_translate("MainWindow", "Temp: 43C°"))
        self.label_25.setText(_translate("MainWindow", "The system is in good shape!"))
        self.label_credit.setText(_translate("MainWindow", "By: Oussama Talaoui"))

